### ISSUE TITLE
Get-CATemplate New-Object : Exception calling ".ctor" with "1" argument(s):

### ISSUE THREAD

**Issue by fullenw1** [Crypt32/PSPKI#62] opened 2019-01-25 10:24 UTC
Hello,

I have no problem with other cmdlets of the module so far.
However, the Get-CATemplate doesn't work for me.

`Get-CATemplate -CertificationAuthority $CA`
`New-Object : Exception calling ".ctor" with "1" argument(s): "There is no such object on the server."`
`At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.4.1.0\Server\Get-CATemplate.ps1:14 char:4`
`+             New-Object PKI.CertificateServices.CATemplate -ArgumentLi ...`
`+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException`
`    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand`

I also tried this, but I get the same error for every Certification Authority

`Get-CertificationAuthority | Get-CATemplate`

I had a look a the code and tried to do it with a class object but I get the same error.

`$CA = [PKI.CertificateServices.CertificateAuthority]::GetCA('Name','SubCA')`

So far, so good! But then I get the same error:

`[PKI.CertificateServices.CATemplate]::new($CA)`
`Cannot convert argument "certificateAuthority", with value:`
`"PKI.CertificateServices.CertificateAuthority[]", for ".ctor" to type`
`"PKI.CertificateServices.CertificateAuthority": "Cannot convert the `
`"PKI.CertificateServices.CertificateAuthority[]" value of type "PKI.CertificateServices.CertificateAuthority[]" to type "PKI.CertificateServices.CertificateAuthority"."`
`At line:1 char:1`
` + [PKI.CertificateServices.CATemplate]::new($CA)`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [], MethodException`
`    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument`

**Comment by Crypt32** [comment] 2019-01-28 13:16
`$CA = [PKI.CertificateServices.CertificateAuthority]::GetCA('Name','SubCA')` returns a collection of CA objects. You need to pass a single object in the constructor:

```
[PKI.CertificateServices.CATemplate]::new($CA[0])
```
this should work. Interesting, what returns `$CA` variable.

**Comment by fullenw1** [comment] 2019-01-31 09:35
I get the same error

> `PS> [PKI.CertificateServices.CATemplate]::new($CA[0])`
Exception calling ".ctor" with "1" argument(s): "There is no such object on the server."`
`At line:1 char:1`
`+ [PKI.CertificateServices.CATemplate]::new($CA[0])`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException`
`    + FullyQualifiedErrorId : DirectoryServicesCOMException`

**$CA type**

> `PS> $CA.GetType()`
`IsPublic IsSerial Name                                     BaseType`
`-------- -------- ----                                     --------`
`True     True     CertificateAuthority[]                   System.Array`

**$CA members**

> `PS> $CA|gm`
`TypeName: PKI.CertificateServices.CertificateAuthority`
`Name                       MemberType Definition`
`----                       ---------- ----------`
`Equals                     Method     bool Equals(System.Object obj)`
`GetCACerts                 Method`
`System.Security.Cryptography.X509Certificates.X509Certificate2Collection GetCACerts()`
`GetCAExchangeCertificate   Method     System.Security.Cryptography.X509Certificates.X509Certificate2`
`GetCAExchangeCertificate()`
`GetDbReader                Method`
`SysadminsLV.PKI.Management.CertificateServices.Database.AdcsDbReader`
`GetDbReader(SysadminsLV.PKI.Management.CertificateServices.Database.AdcsDbViewTableName table)`
`GetHashCode                Method     int GetHashCode()`
`GetMyRoles                 Method     PKI.Security.CARoleEnum GetMyRoles()`
`GetSchema                  Method     PKI.CertificateServices.DB.Schema[]`
`GetSchema(PKI.CertificateServices.DB.TableList table)`
`GetSecurityDescriptor      Method     PKI.Security.AccessControl.CASecurityDescriptor`
`GetSecurityDescriptor()`
`GetType                    Method     type GetType()`
`Ping                       Method     bool Ping()`
`PublishCRL                 Method     void PublishCRL(bool deltaOnly, bool updateFilesOnly)`
`Restart                    Method     void Restart()`
`Start                      Method     void Start()`
`Stop                       Method     void Stop()`
`ToString                   Method     string ToString()`
`UpdateEnrollmentServiceUri Method     void UpdateEnrollmentServiceUri()`
`BaseCRL                    Property   System.Security.Cryptography.X509Certificates.X509CRL2 BaseCRL {get;}`
`Certificate                Property   System.Security.Cryptography.X509Certificates.X509Certificate2`
`Certificate {get;}`
`ComputerName               Property   string ComputerName {get;}`
`ConfigString               Property   string ConfigString {get;}`
`DeltaCRL                   Property   System.Security.Cryptography.X509Certificates.X509CRL2 DeltaCRL {get;}`
`DisplayName                Property   string DisplayName {get;}`
`DistinguishedName          Property   string DistinguishedName {get;}`
`EnrollmentServiceURI       Property   PKI.CertificateServices.CESUri[] EnrollmentServiceURI {get;set;}`
`IsAccessible               Property   bool IsAccessible {get;}`
`Name                       Property   string Name {get;}`
`OperatingSystem            Property   string OperatingSystem {get;}`
`RegistryOnline             Property   bool RegistryOnline {get;}`
`ServiceStatus              Property   string ServiceStatus {get;}`
`SetupStatus                Property   PKI.CertificateServices.SetupStatusEnum SetupStatus {get;}`
`Type                       Property   string Type {get;}`

**$CA content anonymized**

> `PS> $CA|fl *`
`Name                 : SubCa`
`DisplayName          : SubCa`
`ComputerName         : SubCaComputer.MyDomain.com`
`ConfigString         : SubCaComputer.MyDomain.com\SubCa`
`DistinguishedName    : CN=SubCa,CN=Enrollment Services,CN=Public MyDomain`
`Services,CN=Services,CN=Configuration,DC=MyDomain,DC=com`
`Type                 : Enterprise Subordinate CA`
`OperatingSystem      : Microsoft Windows Server 2012 R2 Standard`
`IsAccessible         : True`
`RegistryOnline       : True`
`ServiceStatus        : Running`
`SetupStatus          : ServerInstall, ClientInstall, SecurityUpgraded, ServerIsUptoDate`
`Certificate          : [Subject]`
`                         CN=SubCa, DC=MyDomain, DC=com`
`                       [Issuer]`
`                         CN=RootCA`
`                      [Serial Number]`
`                         5B000000048C495F4D00137E09000000000004`
`                       [Not Before]`
`                         04/04/2017 19:09:31`
`                       [Not After]`
`                         04/04/2027 19:19:31`
`                       [Thumbprcom]`
`                         9D7009D1B4E3DDBBBFB49A72496C949EECBD5984`
`BaseCRL              : System.Security.Cryptography.X509Certificates.X509CRL2`
`DeltaCRL             : System.Security.Cryptography.X509Certificates.X509CRL2`
`EnrollmentServiceURI : `

**Comment by Crypt32** [comment] 2019-01-31 21:37
Can you provide a stack trace? `$error[0].Exception.InnerException.StackTrace`

**Comment by Crypt32** [comment] 2019-02-05 15:49
Can you open ADSI Editor (adsiedit.msc) connect to configuration naming context and find this container: `CN=Certificate Templates,CN=Public Key Services,CN=Services,CN=Configuration`? Are there objects under this container?

**Comment by fullenw1** [comment] 2019-02-05 17:11
Yes, there are 72 templates.

![image](https://user-images.githubusercontent.com/23318240/52290880-61c73800-2971-11e9-8835-b3ee83f9e28f.png)

![image](https://user-images.githubusercontent.com/23318240/52290818-3cd2c500-2971-11e9-8bed-bd328b544a77.png)

**Comment by Crypt32** [comment] 2019-02-05 17:13
Ok, can you open `certsrv.msc` MMC snap-in and check if all templates are shown correctly in Certificate Templates folder?

**Comment by fullenw1** [comment] 2019-02-05 17:36
Yes all published certificates are present in the global list.
Was it what you meant by "shown correctly" ?

**Comment by Crypt32** [comment] 2019-02-05 17:37
> Was it what you meant by "shown correctly" ?

I mean there are no empty lines or entries with red circles.

**Comment by fullenw1** [comment] 2019-02-05 17:40
Ok. I have never seen this situation before...
I checked again and there are no empty lines nor entries with red circles.

**Comment by Crypt32** [comment] 2019-02-05 18:01
What OS you are running (where you execute PSPKI module)?

**Comment by Crypt32** [comment] 2019-02-05 18:22
Also, I would suggest to run this command: `Get-CertificateTemplate`.

1. Does it fail?
2. Does it fail on all templates or specific one?
3. If the cmdlet fails only on a specific template, can you determine which one fails (templates are ordered alphabetically and should have the same ordering as in ADSI Editor)
4. Can you export template by using `ldifde.exe` tool and send it to me privately?

**Comment by fullenw1** [comment] 2019-02-06 14:07
The `Get-CertificateTemplate` cmdlet returns 72 templates.
There is no error.
I've exported all templates. Just sent you a request...
I will attach the file to the IM message.
Or maybe do you have another way to send you a file...

**Comment by fullenw1** [comment] 2019-02-06 14:17
I am running the PSPKI module on a Windows 7.
But I Tried on a Windows 2012 R2 and I have the same error.

**Comment by PatrickOnGit** [comment] 2019-02-06 16:09
Hi fullenw1

May I ask if you enabled any template in that particular CA? As Get-CertificateTemplate queries AD to find any available template in AD but Get-CATemplate asks the CA which templates have been added to enroll on that CA.

Best regards
Patrick

**Comment by Crypt32** [comment] 2019-02-06 16:31
@PatrickOnGit I do believe that there are templates assigned to CA server, because stacktrace provided here: https://github.com/Crypt32/PSPKI/issues/62#issuecomment-460636569 suggests that. The code goes to CertificateTemplate constructor and fails when the code attempts to fetch template information. 

I thought that there is a misconfigured template, however it doesn't seem to be the case, because `Get-CertificateTemplate` enumerate all templates with their properties. So `CertificateTemplate` class can be excluded from the issue.

I have an idea what to check. What returns ICertAdmin interface:

```
$CertAdmin = new-object -com CertificateAuthority.Admin
$CertAdmin.GetCAProperty($ca.ConfigString,0x1d,0,4,)
```

and post the output. I can think of weird certificate template name with disallowed characters in template name. My code can escape disallowed characters, but there may be a case when they are escaped twice, thus giving an error.

**Comment by fullenw1** [comment] 2019-02-07 19:48
@PatrickOnGit 
Yes there are several templates enrolled on the CA.

@Crypt32 
Without flag (the 5th argument), the command returns an error
> `At line:1 char:52`
`+ $CertAdmin.GetCAProperty($ca.ConfigString,0x1d,0,4,)`
`+                                                    ~`
`Missing expression after ','.`
`    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException`
`    + FullyQualifiedErrorId : MissingExpressionAfterToken`

I tried with the ASCII flag but maybe my syntax is not correct...

> `PS> $ca`
`
DisplayName                              ComputerName              IsAccessible ServiceStatus Type`
`-----------                              ------------              ------------ ------------- ----`
`SubCa                                 MyComputerName True         Running       Enterprise Subordinate CA`
`
PS> $CertAdmin`
`System.__ComObject`
`
PS> $CertAdmin.GetCAProperty($ca.ConfigString,0x1d,0,4,'CV_OUT_HEXASCII')`
`Object reference not set to an instance of an object.`
`At line:1 char:1`
`+ $CertAdmin.GetCAProperty($ca.ConfigString,0x1d,0,4,'CV_OUT_HEXASCII')`
`+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException`
`    + FullyQualifiedErrorId : System.NullReferenceException`

**Comment by Crypt32** [comment] 2019-02-07 19:57
Sorry, there was a typo. Try the sample again.

**Comment by fullenw1** [comment] 2019-02-07 20:08
Which one?
Same command line with or without the 5th argument?

**Comment by fullenw1** [comment] 2019-02-07 20:14
I have checked all template names (not the displayname).
There are only letters, numbers, hyphens and underscores.

There was also a name with a space. I removed the space and tried again but I get the same error.
Anyway the template with the space inside the name was not enrolled on the CA.
Thus I think this should have no incidence on the `Get-CATemplate` cmdlet.

**Comment by fullenw1** [comment] 2019-02-07 20:20
I've just sent you the LDF export.

**Comment by Crypt32** [comment] 2019-02-07 20:20
I fixed the call:
```
$CertAdmin = new-object -com CertificateAuthority.Admin
$CertAdmin.GetCAProperty($ca.ConfigString,0x1d,0,4,0)
```

**Comment by fullenw1** [comment] 2019-02-07 20:26
This works fine.
There is just a weird empty line between template 9 and 10...

> `PS> $CertAdmin.GetCAProperty($ca.ConfigString,0x1d,0,4,0)
Template1
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.1141447.9359067
Template2
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.9616680.6865592
Template3
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.6253539.6967850
Template4
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.16513310.15239775
Template5
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.10578596.7164893
Template6
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.12031352.5518132
Template7
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.11084811.9677071
Template8
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.3876726.15313120
Template9`

> `Template10
1.3.6.1.4.1.311.21.8.11499494.5896061.4475526.16118290.15798145.205.4944878.5042499`

**Comment by fullenw1** [comment] 2019-02-07 20:29
Oh! Just reformatted my la comment and noticed that there is no OID for template 9 in the output...

**Comment by Crypt32** [comment] 2019-02-07 20:34
Yes, missing OID is the reason why `Get-CATemplate` fails. Does this template exist in AD? If yes, does it have an object identifier in attribute editor (in adsiedit.msc)?

**Comment by fullenw1** [comment] 2019-02-07 20:49
Removed this one from the CA and now it works!
`Get-CATemplate` has no error anymore :)

Which attribute should I look for in Adsiedit?
I can't see anything like an OID for any template...

It's strange because with `Get-CertificateTemplate -Name MyTemplate|% oid` I can see the OID of the buggy template like I can see it for other working templates.

**Comment by fullenw1** [comment] 2019-02-07 20:52
In the export I have sent you, the template is at line 2512.
You can see its OID at line 2523.

**Comment by Crypt32** [comment] 2019-02-07 20:52
Attribute is called `ms-PKI-Cert-Template-OID`.

**Comment by fullenw1** [comment] 2019-02-07 20:55
In Adsiedit, this attribute is <not set> for all templates. That's weird... :)

If you can have a look at my file...
The template is at line 2512.
You can see its OID at line 2523.

**Comment by Crypt32** [comment] 2019-02-07 20:59
Indeed weird, but sometimes happens. May be a bug in `ICertAdmin` interface implementation.

**Comment by fullenw1** [comment] 2019-02-07 21:05
Ok I will try creating a new template with the same properties and delete the old one.

**Comment by fullenw1** [comment] 2019-02-07 21:34
Ok I've found the reason :)
The **Authenticated Users** permission had been removed.
It should at least be **Read**.
Despite my account is a domain admin account and furthermore my account is explicitly set with **Full Control** permissions on this template, the template needs this specific permission for the `Get-CATemplate` cmdlet to run without error...

Woao!!! Thank you very much for the time you spent helping me to figure this out.
If you wouldn't be in another country I would have payed you a beer :)
But who knows... Maybe one day we will meet in person...

Furthermore, I want to thank you for the PSPKI module which is very handy. I use it a lot :)
Thanks a lot!!!

**Closed** 2019-02-07 21:34 UTC
Labels: Investigate, non-issue

**Comment by madburg** [comment] 2024-08-31 22:43
> Ok I've found the reason :) The **Authenticated Users** permission had been removed. It should at least be **Read**. Despite my account is a domain admin account and furthermore my account is explicitly set with **Full Control** permissions on this template, the template needs this specific permission for the `Get-CATemplate` cmdlet to run without error...
> 
> Woao!!! Thank you very much for the time you spent helping me to figure this out. If you wouldn't be in another country I would have payed you a beer :) But who knows... Maybe one day we will meet in person...
> 
> Furthermore, I want to thank you for the PSPKI module which is very handy. I use it a lot :) Thanks a lot!!!

The root cause here is that the Certificate Authority **must** be able to permissioned to 'read' the CA template; you having admin access has no bearing, it is not a bug of any sort.

The Certificate Authority is able to do so in virtue of the default "Authenticated  Users" "Read" permission (as you noticed you had removed and but no other object added to all the CA itself to read the template, thus once you publish the template, the CA can not read it to offer it and all calls fail).

There are many time where you would not want "Authenticated  Users" to be aware a template exists (obfuscate existence) we document and educate any new personnel that the CA object or AD security group containing the CA must be added to each and every CA template that is created, and "Authenticated  Users" is removed and replaced with corresponding requirement (e.g. domain computers, domain controllers, custom AD Security group containing computer or user objects that can enroll for stated certificate being published). 

Old thread but I reference it sometimes when troubleshoot a new client PKI issues. The least I can do for the breadth of knowledge I have gained through the years from Vadmins and PKISolutions
